# -*- coding: utf-8 -*-
"""Entornos_busqueda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ooPoyvhnFz3PY_03vkROOfrsIDCT6eib
"""

# Archivo: entorno_busqueda.py
# Descripción: Plantilla para la formalización de un problema de búsqueda espacial.

class ProblemaBusquedaLaberinto:
    def __init__(self):
        # 1. ESTADO INICIAL: (fila, columna)
        self.estado_inicial = (0, 0)

        # 2. META: (fila, columna)
        self.meta = (4, 4)

        # EL ENTORNO (Espacio de estados): 0 = casilla libre, 1 = obstáculo
        self.mapa = [
            [0, 0, 0, 1, 0],
            [1, 1, 0, 1, 0],
            [0, 0, 0, 0, 0],
            [0, 1, 1, 1, 0],
            [0, 0, 0, 0, 0]
        ]
        self.filas_max = len(self.mapa)
        self.cols_max = len(self.mapa[0])

    def acciones(self, estado):
        """
        Componente 3: ACCIONES LEGALES
        Dado un estado actual (f, c), retorna una lista de acciones posibles
        (ej. ['ARRIBA', 'ABAJO', 'IZQUIERDA', 'DERECHA']) que no se salgan
        del mapa ni choquen contra un muro (1).
        """
        acciones_validas = []
        f, c = estado

        # Validación NORTE (ARRIBA): La fila disminuye. Debe ser >= 0 y no ser obstáculo.
        if f - 1 >= 0 and self.mapa[f - 1][c] == 0:
            acciones_validas.append('ARRIBA')

        # Validación SUR (ABAJO): La fila aumenta. Debe ser menor a filas_max y no ser obstáculo.
        if f + 1 < self.filas_max and self.mapa[f + 1][c] == 0:
            acciones_validas.append('ABAJO')

        # Validación OESTE (IZQUIERDA): La columna disminuye. Debe ser >= 0 y no ser obstáculo.
        if c - 1 >= 0 and self.mapa[f][c - 1] == 0:
            acciones_validas.append('IZQUIERDA')

        # Validación ESTE (DERECHA): La columna aumenta. Debe ser menor a cols_max y no ser obstáculo.
        if c + 1 < self.cols_max and self.mapa[f][c + 1] == 0:
            acciones_validas.append('DERECHA')

        return acciones_validas

    def modelo_transicion(self, estado, accion):
        """
        Componente 4: MODELO DE TRANSICIÓN
        Dado un estado y una acción legal, retorna el nuevo estado resultante (f_nueva, c_nueva).
        """
        f, c = estado

        if accion == 'ARRIBA':
            return (f - 1, c)
        elif accion == 'ABAJO':
            return (f + 1, c)
        elif accion == 'IZQUIERDA':
            return (f, c - 1)
        elif accion == 'DERECHA':
            return (f, c + 1)

        return estado

    def prueba_meta(self, estado):
        """
        Componente 5: PRUEBA DE META
        Retorna True si el estado evaluado es igual a la meta, False en caso contrario.
        """
        return estado == self.meta

    def costo_ruta(self, estado_actual, accion, estado_siguiente):
        """
        Componente 6 (Opcional pero recomendado): COSTO DE RUTA
        Retorna el costo numérico de ejecutar la acción.
        En esta cuadrícula, cada movimiento cuesta 1.
        """
        return 1

# --- ZONA DE PRUEBAS ---
if __name__ == "__main__":
    entorno = ProblemaBusquedaLaberinto()

    print("=== TEST DEL ENTORNO DE BÚSQUEDA ===")

    # Prueba 1: Estado inicial
    estado_prueba = entorno.estado_inicial
    print(f"\n[Prueba 1] Estado inicial: {estado_prueba}")
    print(f"¿Es meta?: {entorno.prueba_meta(estado_prueba)}")
    posibles_acciones = entorno.acciones(estado_prueba)
    print(f"Acciones legales desde el inicio: {posibles_acciones}")
    if posibles_acciones:
        print(f"Transición simulada con '{posibles_acciones[0]}': {entorno.modelo_transicion(estado_prueba, posibles_acciones[0])}")

    # Prueba 2: Casilla con obstáculos adyacentes (0, 2)
    estado_obstaculo = (0, 2)
    print(f"\n[Prueba 2] Estado adyacente a muro en (0,3): {estado_obstaculo}")
    print(f"Acciones legales esperadas [ABAJO, IZQUIERDA]: {entorno.acciones(estado_obstaculo)}")

    # Prueba 3: Prueba de Meta
    estado_meta_prueba = (4, 4)
    print(f"\n[Prueba 3] Estado en Meta: {estado_meta_prueba}")
    print(f"¿Es meta?: {entorno.prueba_meta(estado_meta_prueba)}")